version: "3.8"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        REACT_APP_SERVER_URI: ${HOSTNAME:-localhost}:8000
    depends_on:
      - server
    ports:
      - 3000:80
    networks:
      - graphql
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - FRONTEND_URL=http://${HOSTNAME:-localhost}:3000
      - DATABASE_URL=mongodb://database:27017
      - ENGINE_CACHE_URL=redis://engineCache:6379
      - JUDGE_URL=http://judge:9000
      - SECRETS_DIR=/run/secrets
      - SERVER_PORT=8000
    secrets:
      - access_token
      - judge_token
      - refresh_token
    depends_on:
      - database
      - engineCache
      - judge
    ports:
      - 8000:8000
    networks:
      - backend
      - graphql
  judge:
    container_name: judge
    build: ./judge
    environment:
      - JUDGE_PORT=9000
      - SECRETS_DIR=/run/secrets
    ports:
      - 9000:9000
    networks:
      - backend
    secrets:
      - judge_token
  database:
    container_name: database
    image: mongo:4.4.5
    volumes:
      - /Volumes/mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - backend
  engineCache:
    container_name: engineCache
    image: redis:6.2.3-alpine
    ports:
      - 6379:6379
    networks:
      - backend
secrets:
  access_token:
    file: ./secrets/access_token
  judge_token:
    file: ./secrets/judge_token
  refresh_token:
    file: ./secrets/refresh_token
networks:
  backend:
  graphql:
