version: "3.8"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./web/Dockerfile
      args:
        REACT_APP_SERVER_URI: 192.168.50.191:8000
    depends_on:
      - server
    ports:
      - 3000:80
    networks:
      - graphql
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      - FRONTEND_URL=http://192.168.50.191:3000|http://localhost:3000
      - DATABASE_URL=mongodb://192.168.50.191:27017
      - ENGINE_CACHE_URL=redis://192.168.50.191:6379
      - GRAPHQL_PORT=8000
      - SECRETS_DIR=/run/secrets
    secrets:
      - access_token
      - refresh_token
    depends_on:
      - mongo
      - redis
    ports:
      - 8000:8000
    networks:
      - database
      - graphql
  mongo:
    container_name: mongo
    image: mongo:4.4.1
    volumes:
      - /Volumes/mongodata:/data/db
    ports:
      - 27017:27017
    networks:
      - database
  redis:
    container_name: redis
    image: redis:6.2.1-alpine
    ports:
      - 6379:6379
    networks:
      - database
secrets:
  access_token:
    file: ./secrets/access_token
  refresh_token:
    file: ./secrets/refresh_token
networks:
  database:
  graphql:
