@startuml stateDiagram
hide empty description

state AwaitingPlayers
state AwaitingSelection
state ShowingClue
state AwaitingResponse
state ShowingResult
state VerifyingResult
state ShowingVerifiedResult

state join <<choice>>
state answerClue <<choice>>
state voteOnResult <<choice>>

title \n=Engine State\n

[*] -> AwaitingPlayers : host()
AwaitingPlayers --> join : join()
join --> AwaitingPlayers : [more space]
join --> AwaitingSelection : [game full]
AwaitingSelection --> ShowingClue : selectClue()
AwaitingSelection --> AwaitingSelection : [timeout]
AwaitingSelection --> [*] : [game over]
ShowingClue --> AwaitingResponse: buzzIn()
ShowingClue --> ShowingResult: [timeout]
AwaitingResponse --> answerClue : answerClue() \n or [timeout]
answerClue --> ShowingResult : [correct] or \n [everyone wrong]
answerClue --> ShowingClue : [incorrect]
ShowingResult --> VerifyingResult : protestResult()
VerifyingResult --> voteOnResult : voteOnResult() \n or [timeout]
voteOnResult --> VerifyingResult : [outstanding votes]
voteOnResult --> ShowingVerifiedResult : [all votes counted]
ShowingResult --> AwaitingSelection : [timeout]
ShowingVerifiedResult --> AwaitingSelection : [timeout]

@enduml